name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] <short description>"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve RoboticGen! Please describe the feature you'd like to see.
  
  - type: input
    id: scope
    attributes:
      label: Affected Project or Module
      placeholder: "e.g. obo-play-sdk, obo-code-web"

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful or needed?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe what the feature should do.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or Workarounds
      description: Are there other solutions you have considered?
